baseURL = "https://aoldoni.com/"
languageCode = "en-us"
title = "Alisson Oldoni's personal website"
theme = "minimal"
#disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = "UA-112753163-1"

[params]
    author = "Alisson Oldoni"
    welcome = "Alisson Oldoni's"
    #profilePic = "Martin-138.jpg"
    description = "personal website... Welcome!"
    intro = "You can know more about me [here](/cv/) and [here](/about-me/)."
    githubUsername = "aoldoni"
    accent = "darkred"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["python", "php", "java"]
    css = ["css/intro.css", "css/text.css", "css/player.css"]
    js = ["https://cdn.jsdelivr.net/npm/amplitudejs@3.2.3/dist/amplitude.js", "js/player.js"]
    copyright = "&copy; Alisson Oldoni. All rights reserved. Powered by [Hugo](https://gohugo.io) and [Minimal](https://github.com/calintat/minimal)."

[[menu.main]]
    url = "/"
    name = "Index"
    weight = 1

[[menu.main]]
    url = "/writings/"
    name = "Writings"
    weight = 2
    
[[menu.main]]
    url = "/cv/"
    name = "Curriculum Vit√¶"
    weight = 3

[[menu.main]]
    url = "/music/"
    name = "Music"
    weight = 4

[[menu.main]]
    url = "/about-me/"
    name = "About me"
    weight = 5

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:aoldoni@gmail.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/aoldoni/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/aoldoni/"
    name = "twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/aoldoni/"
    name = "linkedin"
    weight = 4

[taxonomies]
  tag = "tags"
  category = "categories"